### ISSUE TITLE
How to set args when  running train_hetero.py

### ISSUE THREAD

**Issue by ad56917783** [IDSIA/hhmarl_2D#1]
1.Is it essential to train every level of the hetero with "--level" from 1 to 5?
2.Is it essential to set the argument "--restore=True" when "--level">=2?
3.If  ValueError  "[[nan,nan,nan,...,nan,nan],...,[nan,nan,...,nan,nan]" is raised,and logger warns "NaN or Inf in input data",should I restore the model from lower level or retrain the model from level=1?

**Comment by ardian-selmonaj** [comment]
1. You can also directly start with level 2 or 3, but not from level 4 or 5. Because L4 and L5 need the models of L3 for the opponents.
2. yes, otherwise training starts again from beginning.
3. I don't know I didn't get a ValueError

Anyhow, I will upload an updated version in the coming days ...
