### ISSUE TITLE
RuntimeError: Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm)

### ISSUE THREAD

**Issue by idazhuang** [IDSIA/hhmarl_2D#12]
![微信截图_20241115210514](https://github.com/user-attachments/assets/b32dd941-d0f7-4459-ba92-f76dba4ba7fc)
Hello, I encountered this issue during Level 4 training, which I didn't experience in the previous levels. How should I solve it?

**Comment by ardian-selmonaj** [comment]
Hello, it seems like you have done training up to Level 3 on GPU and then switched to CPU. It's hardly any other reason for this error. I generally recommend training everything on CPU.

**Comment by idazhuang** [comment]
Thank you for your reply，after I retrain on the CPU, I have solved this problem. Thanks again!
