### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [IDSIA/hhmarl_2D#5]
I stumbled across your project while researching about possible search and rescue reinforcement learning environments. It seems interesting. I am wondering under what license is this project released under ? Thank you.

**Comment by ardian-selmonaj** [comment]
according to our regulations we don't have any restrictions or license.

**Comment by suprafun** [comment]
I mean source code license, I would like to study your implementation to learn from it. Thank you.

**Comment by ardian-selmonaj** [comment]
you are free to do so, we really don't have any restrictions.
