### ISSUE TITLE
How to write an evaluation environment for 3v3 or 4v4, 5v5etc.?

### ISSUE THREAD

**Issue by YangRongtai** [IDSIA/hhmarl_2D#6]
Hello, I apologize for the interruption. I have been trying to learn your method and have completed training the agent. I would like to evaluate the performance of the strategy at different scales, such as how the "fight" strategy performs in situations like 3v3, 4v4, etc. I made an attempt but was not successful. I would like to ask you how to write evaluation environments for 3v3 and 4v4 in both LowLevel-env and HighLevel-env. If possible, could you provide an example for 3v3 or 4v4? I look forward to your reply. Thank you very much~

**Comment by ardian-selmonaj** [comment]
Hi, just added the evaluation function. Please also have a look at the new description. Have fun!

**Comment by YangRongtai** [comment]
Thank you for all your help and support, I am truly grateful. Wishing you all the best.




---Original---
From: ***@***.***&gt;
Date: Fri, May 3, 2024 04:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IDSIA/hhmarl_2D] How to write an evaluation environment for 3v3or 4v4, 5v5etc.? (Issue #6)




 
Hi, just added the evaluation function. Please also have a look at the new description. Have fun!
